name: Generated APK AAB (Upload - Create Artifact To Github Action)

env:
  # The name of the main module repository
  main_project_module: app

on:

  push:
    branches:
      - 'release/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: JDK Installation
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build app bundle release
        run: ./gradlew assembleProdMainnet
      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: LunifyVault
          path: |
            app/build/outputs/apk/prodMainnet/release/
          exclude: |
            **/*.json
